# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish finder for nodejs

on:
  workflow_dispatch:
  push:
    tags:
      - 'js-finder-[0-9]*.[0-9]*.[0-9]*'

permissions:
  contents: write
  pull-requests: write
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
        working-directory: finder/nodejs
      - run: npm test
        working-directory: finder/nodejs

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v7
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
        working-directory: finder/nodejs
      - run: npm publish
        name: Publish the package
        working-directory: finder/nodejs
